"""IX-IntentRealityLoop package.

IX-IntentRealityLoop is a source-available evaluation runtime for governed
sensorimotor agency loops. It is designed to bind intent, interpretation,
permission, bounded action, feedback, memory update, and replayable evidence
without self-authorizing or overclaiming AGI.
"""

from __future__ import annotations

from ix_intent_reality_loop.action import (
    ActionMode,
    BoundedActionDecision,
    plan_bounded_action,
    validate_bounded_action_decision,
)
from ix_intent_reality_loop.arbiter import (
    FourthEyeDecision,
    arbitrate_fourth_eye_decision,
    validate_fourth_eye_decision,
)
from ix_intent_reality_loop.benchmarks import (
    BenchmarkExpectedOutcome,
    BenchmarkRunResult,
    BenchmarkScenario,
    BenchmarkScenarioKind,
    benchmark_catalog,
    run_benchmark_scenario,
    validate_benchmark_catalog,
)
from ix_intent_reality_loop.blackfox_handoff import (
    BlackFoxGovernanceHandoff,
    GovernanceGate,
    GovernanceReviewItem,
    GovernanceRisk,
    build_blackfox_governance_handoff,
    validate_blackfox_governance_handoff,
)
from ix_intent_reality_loop.comparison import (
    LaneComparisonRecord,
    build_lane_comparison_record,
    validate_lane_comparison_record,
)
from ix_intent_reality_loop.core import (
    AuthorityState,
    BoundedScore,
    DecisionDisposition,
    EvidenceStatus,
    ValidationFinding,
    ValidationSeverity,
)
from ix_intent_reality_loop.delta import (
    OutcomeDelta,
    OutcomeDeltaStatus,
    build_outcome_delta,
    validate_outcome_delta,
)
from ix_intent_reality_loop.doctrine import (
    DoctrineRule,
    DoctrineSeverity,
    assert_no_prohibited_claims,
    doctrine_catalog,
    doctrine_index,
    find_prohibited_claims,
)
from ix_intent_reality_loop.evidence import (
    EvidenceBundle,
    EvidenceItem,
    EvidenceItemKind,
    build_evidence_bundle,
    validate_evidence_bundle,
)
from ix_intent_reality_loop.export import (
    ArtifactExport,
    canonical_json,
    export_artifact,
    export_artifact_json,
    export_many_artifacts,
    sha256_hex_for_payload,
    validate_artifact_export,
    write_artifact_export,
)
from ix_intent_reality_loop.feedback import (
    FeedbackModality,
    FeedbackOutcome,
    RealityFeedbackFrame,
    RealityFeedbackSignal,
    build_reality_feedback_frame,
    validate_reality_feedback_frame,
)
from ix_intent_reality_loop.focus import (
    FocusRequirement,
    FocusRisk,
    FocusSignal,
    FocusSplitRecord,
    build_focus_split_record,
    validate_focus_split_record,
)
from ix_intent_reality_loop.intent import (
    IntentPacket,
    IntentSource,
    IntentStatus,
    build_user_intent_packet,
    validate_intent_packet,
)
from ix_intent_reality_loop.kernel_handoff import (
    KernelDonorCapability,
    KernelDonorStatus,
    KernelWave6DonorPacket,
    build_kernel_wave6_donor_packet,
    validate_kernel_wave6_donor_packet,
)
from ix_intent_reality_loop.lanes import (
    ExecutionLaneKind,
    ExecutionLaneResult,
    ExecutionLaneStatus,
    build_interpreted_lane_result,
    build_literal_lane_result,
    build_self_surpass_lane_result,
    validate_execution_lane_result,
)
from ix_intent_reality_loop.manifest import (
    DigestAlgorithm,
    DigestRecord,
    ReplayManifest,
    build_digest_record,
    build_replay_manifest,
    validate_replay_manifest,
)
from ix_intent_reality_loop.memory import (
    MemoryBindingAction,
    MemoryBindingDecision,
    MemoryBindingReason,
    build_memory_binding_decision,
    validate_memory_binding_decision,
)
from ix_intent_reality_loop.memory_ledger import (
    MemoryLedger,
    MemoryLedgerEntry,
    apply_memory_binding_decision,
    build_memory_ledger_entry,
    validate_memory_ledger,
)
from ix_intent_reality_loop.negative_controls import (
    NegativeControlKind,
    NegativeControlOutcome,
    NegativeControlReport,
    NegativeControlResult,
    run_negative_control_suite,
    validate_negative_control_report,
)
from ix_intent_reality_loop.permission import (
    ConsentRecord,
    ConsentStatus,
    PermissionGateResult,
    PermissionScope,
    evaluate_permission_gate,
    validate_permission_gate_result,
)
from ix_intent_reality_loop.pipeline import (
    IntentRealityLoopAssembly,
    assemble_benchmark_evidence,
    build_replay_log_from_run_result,
    validate_assembly_links,
)
from ix_intent_reality_loop.replay import (
    ReplayEvent,
    ReplayEventLog,
    ReplayEventType,
    build_replay_event,
    validate_replay_event_log,
)
from ix_intent_reality_loop.safety import (
    InteractionState,
    SafetyGateResult,
    SafetyLevel,
    SafetyMap,
    SafetySignal,
    evaluate_safety_gate,
    validate_safety_gate_result,
)

__all__ = [
    "ActionMode",
    "ArtifactExport",
    "AuthorityState",
    "BenchmarkExpectedOutcome",
    "BenchmarkRunResult",
    "BenchmarkScenario",
    "BenchmarkScenarioKind",
    "BlackFoxGovernanceHandoff",
    "BoundedActionDecision",
    "BoundedScore",
    "ConsentRecord",
    "ConsentStatus",
    "DecisionDisposition",
    "DigestAlgorithm",
    "DigestRecord",
    "DoctrineRule",
    "DoctrineSeverity",
    "EvidenceBundle",
    "EvidenceItem",
    "EvidenceItemKind",
    "EvidenceStatus",
    "ExecutionLaneKind",
    "ExecutionLaneResult",
    "ExecutionLaneStatus",
    "FeedbackModality",
    "FeedbackOutcome",
    "FocusRequirement",
    "FocusRisk",
    "FocusSignal",
    "FocusSplitRecord",
    "FourthEyeDecision",
    "GovernanceGate",
    "GovernanceReviewItem",
    "GovernanceRisk",
    "IntentPacket",
    "IntentRealityLoopAssembly",
    "IntentSource",
    "IntentStatus",
    "InteractionState",
    "KernelDonorCapability",
    "KernelDonorStatus",
    "KernelWave6DonorPacket",
    "LaneComparisonRecord",
    "MemoryBindingAction",
    "MemoryBindingDecision",
    "MemoryBindingReason",
    "MemoryLedger",
    "MemoryLedgerEntry",
    "NegativeControlKind",
    "NegativeControlOutcome",
    "NegativeControlReport",
    "NegativeControlResult",
    "OutcomeDelta",
    "OutcomeDeltaStatus",
    "PermissionGateResult",
    "PermissionScope",
    "RealityFeedbackFrame",
    "RealityFeedbackSignal",
    "ReplayEvent",
    "ReplayEventLog",
    "ReplayEventType",
    "ReplayManifest",
    "SafetyGateResult",
    "SafetyLevel",
    "SafetyMap",
    "SafetySignal",
    "ValidationFinding",
    "ValidationSeverity",
    "__version__",
    "apply_memory_binding_decision",
    "arbitrate_fourth_eye_decision",
    "assemble_benchmark_evidence",
    "assert_no_prohibited_claims",
    "benchmark_catalog",
    "build_blackfox_governance_handoff",
    "build_digest_record",
    "build_evidence_bundle",
    "build_focus_split_record",
    "build_interpreted_lane_result",
    "build_kernel_wave6_donor_packet",
    "build_lane_comparison_record",
    "build_literal_lane_result",
    "build_memory_binding_decision",
    "build_memory_ledger_entry",
    "build_outcome_delta",
    "build_reality_feedback_frame",
    "build_replay_event",
    "build_replay_log_from_run_result",
    "build_replay_manifest",
    "build_self_surpass_lane_result",
    "build_user_intent_packet",
    "canonical_json",
    "doctrine_catalog",
    "doctrine_index",
    "evaluate_permission_gate",
    "evaluate_safety_gate",
    "export_artifact",
    "export_artifact_json",
    "export_many_artifacts",
    "find_prohibited_claims",
    "plan_bounded_action",
    "run_benchmark_scenario",
    "run_negative_control_suite",
    "sha256_hex_for_payload",
    "validate_action_decision",
    "validate_artifact_export",
    "validate_assembly_links",
    "validate_benchmark_catalog",
    "validate_blackfox_governance_handoff",
    "validate_bounded_action_decision",
    "validate_evidence_bundle",
    "validate_execution_lane_result",
    "validate_focus_split_record",
    "validate_fourth_eye_decision",
    "validate_intent_packet",
    "validate_kernel_wave6_donor_packet",
    "validate_lane_comparison_record",
    "validate_memory_binding_decision",
    "validate_memory_ledger",
    "validate_negative_control_report",
    "validate_outcome_delta",
    "validate_permission_gate_result",
    "validate_reality_feedback_frame",
    "validate_replay_event_log",
    "validate_replay_manifest",
    "validate_safety_gate_result",
    "write_artifact_export",
]

__version__ = "0.1.0"

validate_action_decision = validate_bounded_action_decision
